server:
  port: 8081

spring:
  application:
    name: profile
  datasource:
    url: jdbc:postgresql://localhost:5433/profile_db
    username: profile_user
    password: profile_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
