spring.application.name=profile
spring.datasource.url=jdbc:postgresql://localhost:5432/profile
spring.datasource.username=suprasannabhaumik
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update