server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: profile
              uri: http://profile:8081
              predicates:
                - Path=/api/v1/profiles/**
            - id: favorites
              uri: http://favorites:8084
              predicates:
                - Path=/api/v1/customers/{customerId}/favorites/**
