

spring:
  datasource:
    url: ${FAVORITES_DB_URL:jdbc:postgresql://favorites-db:5432/favorites_db}
    username: ${FAVORITES_DB_USERNAME:favorites_user}
    password: ${FAVORITES_DB_PASSWORD:favorites_password}