server:
  port: 8084

spring:
  application:
    name: favorites
  datasource:
    url: jdbc:postgresql://localhost:5432/favorites
    username: suprasannabhaumik
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true